import {
  EndPointRepository,
  FuncionRepository,
  GenericNomencladorRepository,
  MenuRepository,
  RolRepository,
  LogHistoryRepository,
  UserRepository,
  RegistroDiarioRepository,
  MovimientoInventarioRepository,
  ProductoRepository,
  QrRepository,
  ConteoInventarioRepository,
  NivelStockRepository,
} from './repository';
import {
  EndPointEntity,
  FuncionEntity,
  LogHistoryEntity,
  MenuEntity,
  RolEntity,
  UserEntity,
  CategoriaEntity,
  AlmacenEntity,
  UnidadEntity,
  UbicacionEntity,
  ProductoEntity,
  MovimientoInventarioEntity,
  RegistroDiarioEntity,
  QrEntity,
  ConteoInventarioEntity,
  NivelStockEntity,
} from './entity';

export const repository = [
  LogHistoryRepository,
  UserRepository,
  RolRepository,
  FuncionRepository,
  EndPointRepository,
  MenuRepository,
  GenericNomencladorRepository,
  RegistroDiarioRepository,
  MovimientoInventarioRepository,
  ProductoRepository,
  QrRepository,
  ConteoInventarioRepository,
  NivelStockRepository,
];
export const entity = [
  EndPointEntity,
  FuncionEntity,
  MenuEntity,
  RolEntity,
  LogHistoryEntity,
  UserEntity,
  CategoriaEntity,
  AlmacenEntity,
  UnidadEntity,
  UbicacionEntity,
  ProductoEntity,
  MovimientoInventarioEntity,
  RegistroDiarioEntity,
  QrEntity,
  ConteoInventarioEntity,
  NivelStockEntity,
];
