export enum Configuration {
  DB_USER = 'DB_USER',
  DB_PASS = 'DB_PASS',
  DB_NAME = 'DB_NAME',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_SYNC = 'DB_SYNC',
  DB_MIGRATIONS_RUN = 'DB_MIGRATIONS_RUN',
  DB_AUTH_SOURCE = 'DB_AUTH_SOURCE',
}
