import {
  AuthController,
  EndPointController,
  FuncionController,
  GenericNomencladorController,
  LogHistoryController,
  MenuController,
  MovimientoInventarioController,
  ProductoController,
  RegistroDiarioController,
  RolController,
  UserController,
  QrController,
  BiController,
  SyncController,
  HealthController,
  ConteoInventarioController,
  FotoPublicaController,
  NivelStockController,
} from './controller';

export const controller = [
  LogHistoryController,
  AuthController,
  UserController,
  RolController,
  GenericNomencladorController,
  EndPointController,
  FuncionController,
  MenuController,
  ProductoController,
  MovimientoInventarioController,
  RegistroDiarioController,
  QrController,
  BiController,
  SyncController,
  HealthController,
  ConteoInventarioController,
  FotoPublicaController,
  NivelStockController,
];
