import { JwtStrategy } from './strategy/jwt.strategy';
import { RefreshStrategy } from './strategy/refresh.strategy';
import {
  AuthService,
  EndPointService,
  FuncionService,
  GenericNomencladorService,
  MenuService,
  RolService,
  SocketService,
  LogHistoryService,
  UserService,
  MovimientoInventarioService,
  ProductoService,
  RegistroDiarioService,
  QrService,
  BiService,
  SyncService,
  SyncRelationService,
  ConteoInventarioService,
} from './service';
import {
  EndPointMapper,
  FuncionMapper,
  GenericNomencladorMapper,
  MenuMapper,
  RolMapper,
  LogHistoryMapper,
  UserMapper,
  MovimientoInventarioMapper,
  ProductoMapper,
  RegistroDiarioMapper,
  QrMapper,
  ConteoInventarioMapper,
} from './mapper';
import { LoggerProvider } from './logger/logger.provider';

export const providers = [
  JwtStrategy,
  RefreshStrategy,
  LogHistoryService,
  LogHistoryMapper,
  LoggerProvider,
  AuthService,
  UserService,
  UserMapper,
  RolMapper,
  FuncionMapper,
  EndPointMapper,
  MenuMapper,
  RolService,
  GenericNomencladorService,
  GenericNomencladorMapper,
  EndPointService,
  FuncionService,
  MenuService,
  SocketService,
  MovimientoInventarioMapper,
  ProductoMapper,
  RegistroDiarioMapper,
  MovimientoInventarioService,
  ProductoService,
  RegistroDiarioService,
  QrMapper,
  QrService,
  BiService,
  SyncService,
  SyncRelationService,
  ConteoInventarioMapper,
  ConteoInventarioService,
];
